---
title: "General Metabolic Analyses"
author: "Sam Dunn"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: 
    fig_height: 8
    fig_width: 8
    toc: yes
---
```{r setup}
#load libraries used
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE, repos='http://cran.us.r-project.org')
    sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("ggplot2", 
              "plyr", 
              "reshape2", 
              "RColorBrewer", 
              "scales", 
              "grid",
              "VennDiagram",
              "vegan",
              "RAM",
              "tidyr",
              "Rmisc",
              "reshape","reshape2",
              "gapminder","magrittr","dplyr","ggpubr","gridExtra","
              patternplot","tibble","gplots","broom","data.table","nlme",
              "devtools","bibtex","tidyverse","multcomp","pander","xtable",
              "XLconnect","ggsignif","ggpubr","ggpmisc","packagemetrics",
              "flextable","multcompView","cowplot","lubridate","lme4")
ipak(packages)


#devtools::install_github("const-ae/ggsignif")
```

```{r}
####Data import####

cv.data=read.csv("compiled_cv.csv")
cv.data<-cv.data %>% 
  gather(key=Date,value=OD_cm,-Substrate,-Rep)
cv.data$Date<-cv.data$Date %>% 
  gsub(pattern="X",replacement="")

metabolism.data=read.csv("compiled metabolism_longform.csv")
chl.data=read.csv("compiled_chl.csv")
field.data=read.csv("fielddata.csv")
eea.df=read.csv("Compiled_EEA.csv")
par.df=read.csv("par.csv")
usgs.df=read.csv("usgs_niles.csv")
water=read.csv("waterchem.wide.csv")
pd=position_dodge(width=0.8)
```


The dates have been redone using lubridate (9/11/2018)
```{r Dates}
###reformat dates####
metabolism.data$Date.Sampled<-mdy(metabolism.data$Date.Sampled)
water$Date<-mdy(water$Date)
field.data$Date<-mdy(field.data$Date)
eea.df$Date.Sampled<-mdy(eea.df$Date.Sampled)
cv.data$Date.Sampled<-mdy(cv.data$Date)
par.df$Date=dmy(par.df$Date) 
usgs.df$Datetime=mdy_hm(usgs.df$timestamp)



metabolism.data$time=metabolism.data$doy-227
metabolism.data$id=seq(1:15)
eea.df$time=metabolism.data$time
cv.data$time=metabolism.data$time
combo.df=cbind(metabolism.data,eea.df[,7:12])
chl.data=droplevels(chl.data[-which(chl.data$Sample=='Cr'),])
chl.data$time=metabolism.data$time
eea.df$id=seq(1:15)
chl.data$id=seq(1:15)
cv.data$id=seq(1:15)
#s.numeric(field.data$xvelocity)
```



```{r Data Cleaning}
####Data cleaning-Metabolism####
metabolism.data$GPP<-ifelse(metabolism.data$GPP<0,0.000001,metabolism.data$GPP)
metabolism.data$Resp<-ifelse(metabolism.data$Resp>0,0.000001,metabolism.data$Resp)
#pc.df=cbind(metabolism.data[1],metabolism.data[3],metabolism.data[5:7],eea.df[8],eea.df[10],eea.df[12])

##chlorophyll a calculation
cv.resp.df=cbind(cv.data,metabolism.data[,5:7])
chl.data$chla_cm=286*(((abs(chl.data$X665B)-abs(chl.data$X750B))-(abs(chl.data$X665A)-abs(chl.data$X750A))*5)/chl.data$area)
chl.data$chl_abs=abs(chl.data$chla_cm)


pc.df=cbind(metabolism.data[1],metabolism.data[3],metabolism.data[5:7],eea.df[8],
            eea.df[10],eea.df[12],chl.data[13],cv.data[4],metabolism.data[8])

##Aggregate Data and Summarize
water.Date=list(unique(water$Date))
no3.sum=aggregate(no3~Date,water,mean)
nh4.sum=aggregate(nh4~Date,water,mean)
srp.sum=aggregate(srp~Date,water,mean)
water.sum=full_join(no3.sum,nh4.sum,by="Date")
water.sum=full_join(srp.sum,water.sum,by="Date")
pc.df=full_join(pc.df,water.sum,by=c("Date.Sampled"="Date"))
pc.df=full_join(pc.df,field.data,by=c("Date.Sampled"="Date"))

write.csv(pc.df, file="env.df")
pc.df=na.omit(pc.df)
metabolism.data=full_join(metabolism.data,water.sum,by=c("Date.Sampled"="Date"))

eea.df=full_join(eea.df,water.sum,by=c("Date.Sampled"="Date"))
```

```{r Remove outliers and re-factor substrates,include=F,eval=F}
####Remove outliers####
outlierKD <- function(dt, var) {
  var_name <- eval(substitute(var),eval(dt))
  na1 <- sum(is.na(var_name))
  m1 <- mean(var_name, na.rm = T)
  par(mfrow=c(2, 2), oma=c(0,0,3,0))
  boxplot(var_name, main="With outliers")
  hist(var_name, main="With outliers", xlab=NA, ylab=NA)
  outlier <- boxplot.stats(var_name)$out
  mo <- mean(outlier)
  var_name <- ifelse(var_name %in% outlier, NA, var_name)
  boxplot(var_name, main="Without outliers")
  hist(var_name, main="Without outliers", xlab=NA, ylab=NA)
  title("Outlier Check", outer=TRUE)
  na2 <- sum(is.na(var_name))
  cat("Outliers identified:", na2 - na1, "n")
  cat("Propotion (%) of outliers:", round((na2 - na1) / sum(!is.na(var_name))*100, 1), "n")
  cat("Mean of the outliers:", round(mo, 2), "n")
  m2 <- mean(var_name, na.rm = T)
  cat("Mean without removing outliers:", round(m1, 2), "n")
  cat("Mean if we remove outliers:", round(m2, 2), "n")
  response <- readline(prompt="Do you want to remove outliers and to replace with NA? [yes/no]: ")
  if(response == "y" | response == "yes"){
    dt[as.character(substitute(var))] <- invisible(var_name)
    assign(as.character(as.list(match.call())$dt), dt, envir = .GlobalEnv)
    cat("Outliers successfully removed", "n")
    return(invisible(dt))
  } else{
    cat("Nothing changed", "n")
    return(invisible(var_name))
  }
}

outlierKD(metabolism.data,Resp)
#yes
outlierKD(metabolism.data,GPP)
#yes
outlierKD(metabolism.data,NEP)
#yes
outlierKD(metabolism.data,Resp_OD)
#no
outlierKD(metabolism.data,GPP_OD)
#no
outlierKD(metabolism.data,NEP_OD)
#no
outlierKD(eea.df,BGT2)
yes
outlierKD(eea.df,NAGT2)
yes
outlierKD(eea.df,PT2)
yes
outlierKD(eea.df,BGT2_OD)
no#
outlierKD(eea.df,NAGT2_OD)
no#
outlierKD(eea.df,PT2_OD)
no#
outlierKD(eea.df,srp)
yes
outlierKD(eea.df,no3)
no
outlierKD(eea.df,nh4)
no
outlierKD(cv.data,OD_cm)
yes
outlierKD(chl.data,chl_abs_OD)
no


```

```{r rename substrates}

metabolism.data$Sample=factor(metabolism.data$Sample,levels=c("H","So","Sh","F","T"),labels=c("PVC","Soft PE","Sheet PE","PS","Tile"))
eea.df$Sample=factor(eea.df$Sample,levels=c("H","So","Sh","F","T"),labels=c("PVC","Soft PE","Sheet PE","PS","Tile"))
cv.data$Substrate=factor(cv.data$Substrate,levels=c("H","So","Sh","F","T"),labels=c("PVC","Soft PE","Sheet PE","PS","Tile"))
chl.data$Sample=factor(chl.data$Sample,levels=c("H","So","Sh","F","T"),labels=c("PVC","Soft PE","Sheet PE","PS","Tile"))
pc.df$Sample=factor(pc.df$Sample,levels=c("H","So","Sh","F","T"),labels=c("PVC","Soft PE","Sheet PE","PS","Tile"))

#integrate PAR
int_par=aggregate(par.df$microMole.s.m2,by=list((substr(par.df$Date,1,385))),mean)
int_par<-int_par %>% 
  rename("Date.Sampled"="Group.1","Summed.PAR"="x")
```

```{r LME-Table1}
#Resp
lme.resp=anova(lme(Resp~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=metabolism.data))
#lme.resp

#GPP
lme.gpp=anova(lme(GPP~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=metabolism.data))
#lme.gpp

#NEP
lme.nep=anova(lme(NEP~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=metabolism.data))
#lme.nep

#BG
lme.bg=anova(lme(BGT2~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=eea.df))
#lme.bg

#NAG
lme.nag=anova(lme(NAGT2~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=eea.df))
#lme.nag

#P
lme.p=anova(lme(PT2~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=eea.df))
#lme.p

#Chl
lme.chl=anova(lme(chl_abs~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=chl.data))
#lme.chl

#CV
cv.data.drop=droplevels(cv.data[-which(cv.data$Date.Sampled=='2017-08-15'),])
lme.cv=anova(lmer(OD_cm~Date.Sampled*Substrate+(Date.Sampled|Substrate),na.action=na.omit,data=cv.data.drop))
#lme.cv
#model fails to converge, basically there is a date effect but no effect of sample
lme.cv=anova(lm(OD_cm~Date.Sampled*Substrate,random=list(id=pdBlocked(list(~1,pdIdent(~Substrate-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=cv.data))
#lme.cv

table1=list(lme.resp,lme.gpp,lme.nep,lme.bg,lme.nag,lme.p,lme.chl)

names(table1)=c("resp","gpp","nep","bg","nag","p","chl")
table1.df=do.call(rbind.data.frame,table1)
table1.df=cbind(rownames(table1.df),table1.df)
rownames(table1.df)=NULL
colnames(table1.df)[1]="assay"
tab.1<-table1.df%>%
  separate(assay,into=c("Assay","Factor"),extra="merge")

problem<-c(".",")")
tab.1$Factor<-tab.1$Factor%>% 
  gsub(pattern=")",replacement="") %>% 
  gsub(pattern="\\.",replacement=" ")






tab.1<-tab.1 %>% 
  filter(Factor!="Intercept")

tab.1[,4:6]<-tab.1[,4:6] %>% 
  signif(digits=3)

htmlTable::htmlTable(tab.1)
DT::datatable(tab.1,
          filter='top',
          extensions='Buttons',
          options = list(dom = 'Bfrtip',buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
write.xlsx(tab.1,file="table1.xlsx")


```

```{r CV figure color}
cv.data=na.omit(cv.data)
theme_set(theme_gray(base_size = 18))
cv.sum=summarySE(cv.data,measurevar="OD_cm",groupvars=c("time","Substrate"))


substrate.plot.cv=ggplot(cv.sum,aes(time,group=Substrate,shape=Substrate,fill=Substrate,na.rm=T,y=OD_cm))+
  geom_point(position=pd,color="black",size=4)+
  geom_line(aes(y=OD_cm,linetype=Substrate),width=.5,position=pd)+
  theme_classic()+
  geom_errorbar(aes(ymin=OD_cm-se,ymax=OD_cm+se,),
                stat="identity",width=.15,na.rm=T,position=pd)+
  ylab(bquote('Optical Density  ('~cm^-2~')'))+
  theme(panel.background=element_blank(),
        legend.title=element_blank(),
        legend.position=c(0.15,0.85),
        axis.text=element_text(size=16),
        axis.title=element_text(size=16),
        legend.text=element_text(size=14))+
  xlab("Days of Incubation")+
  scale_x_continuous(breaks=seq(0,30,5))+
  scale_shape_manual(name="Substrate",values=c(21,22,23,24,25))

substrate.plot.cv
  ggsave("cv.color.jpeg",device="jpeg",width=8.5,height=8.5, units="in")
```



```{r CV-Figure 1}
cv.data=na.omit(cv.data)
theme_set(theme_gray(base_size = 18))
cv.sum=summarySE(cv.data,measurevar="OD_cm",groupvars=c("time","Substrate"))


substrate.plot.cv=ggplot(cv.sum,aes(time,group=Substrate,shape=Substrate,na.rm=T,y=OD_cm))+
  geom_point(position=pd,color="black",size=4,fill="black")+
  geom_line(aes(y=OD_cm,linetype=Substrate),width=.5,position=pd)+
  theme_classic()+
  geom_errorbar(aes(ymin=OD_cm-se,ymax=OD_cm+se,),
                stat="identity",width=.15,na.rm=T,position=pd)+
  ylab(bquote('Optical Density  ('~cm^-2~')'))+
  theme(panel.background=element_blank(),
        legend.title=element_blank(),
        legend.position=c(0.15,0.85),
        axis.text=element_text(size=16),
        axis.title=element_text(size=16),
        legend.text=element_text(size=14))+
  xlab("Days of Incubation")+
  scale_x_continuous(breaks=seq(0,30,5))+
  scale_shape_manual(name="Substrate",values=c(21,22,23,24,25))

substrate.plot.cv
  ggsave("cv.bw.jpeg",device="jpeg",width=8.5,height=8.5, units="in")
```


```{r Figure 2 Metabolism BW}
pd=position_dodge(width=0.8)

bar.df=melt(metabolism.data,id.vars=c("time","Sample"),measure.vars = c("GPP","Resp","NEP"),na.rm=TRUE)


bar.sum=summarySE(bar.df,measurevar="value",groupvars = c("time","variable","Sample"),na.rm=TRUE)
na.omit(bar.sum)
##component plots
gpp.bar.plot=ggplot(bar.sum,aes(time,group=Sample,shape=Sample))+
  geom_point(data=subset(bar.sum,variable=="GPP"), 
             aes(y=value,shape=Sample),stat="identity",fill="black",size=3,position=pd)+
  geom_line(data=subset(bar.sum,variable=="GPP"), 
            aes(y=value, linetype=Sample),width=.5,position=pd)+
  theme_classic()+
  geom_errorbar(data=subset(bar.sum,variable=="GPP"),
                aes(ymin=value-se,ymax=value+se,fill=Sample),
                stat="identity",width=.15,na.rm=T,position=pd)+
  scale_x_continuous(breaks=seq(0,30,5))+
  ylab(bquote(atop('GPP', 'mg O'[2]~''~cm^-2~''~hr^-1)))+
  xlab(NULL)+theme(legend.position = c(0.13,0.78),
                   legend.title=element_blank(),
                   axis.text=element_text(size=16),
                   axis.title=element_text(size=16),
                   legend.text=element_text(size=11),
                   legend.key = element_rect(color="transparent",fill="transparent"))+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))

resp.bar.plot=ggplot(bar.sum,aes(time,group=Sample,shape=Sample))+
  geom_point(data=subset(bar.sum,variable=="Resp"),
             aes(y=value,shape=Sample),stat="identity",
             fill="black",
             size=3,
             position=pd)+
  geom_line(data=subset(bar.sum,variable=="Resp"), 
            aes(y=value, linetype=Sample),
            width=.5,position=pd)+
  theme_classic()+
  geom_errorbar(data=subset(bar.sum,variable=="Resp"),
                aes(ymin=value-se,ymax=value+se,fill=Sample),
                stat="identity",width=.15,na.rm=T,position=pd)+
  scale_x_continuous(breaks=seq(0,30,5),position="top")+
  ylab(bquote(atop('Respiration','mg O'[2]~''~cm^-2~''~hr^-1)))+
  xlab(NULL)+
  theme( legend.title=element_blank(),
                   axis.text=element_text(size=16),
                   axis.title=element_text(size=16),
                   legend.text=element_text(size=14))+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))


nep.bar.plot=ggplot(bar.sum,aes(time,shape=Sample,group=Sample))+
  geom_point(data=subset(bar.sum,variable=="NEP"),na.rm=T,
             aes(y=value, shape=Sample),stat="identity",fill="black",size=3,position=pd)+
  geom_line(data=subset(bar.sum,variable=="NEP"),na.rm=T, 
            aes(y=value, linetype=Sample),width=.5,position=pd)+
  geom_hline(yintercept=0)+theme_classic()+
  geom_errorbar(data=subset(bar.sum,variable=="NEP"),
                aes(ymin=value-se,ymax=value+se,fill=Sample),
                stat="identity",width=.15,na.rm=T,position=pd)+
  scale_x_continuous(breaks=seq(0,30,5))+
  ylab(bquote(atop('NEP','mg O'[2]~''~cm^-2~''~hr^-1)))+
  xlab("Days of Incubation")+
  scale_y_continuous(breaks=seq(-1,1,0.5))+
  theme(legend.position = NULL,
        legend.title=element_blank(),
        axis.text=element_text(size=16),
        axis.title=element_text(size=16),
        legend.text=element_text(size=14))+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))

stacked.bar=ggarrange(gpp.bar.plot+theme(axis.text.x=element_blank()),
                      resp.bar.plot+theme(axis.text.x=element_blank(),legend.position="none"),
                      nep.bar.plot+theme(legend.position="none"),
                      nrow=3,common.legend = FALSE,align="v",heights=c(1,1,1.25))
stacked.bar
ggsave("metabolism.bw.jpeg",width=8.5,height=8.5, units="in")
```

```{r Metabolism color}
pd=position_dodge(width=0.8)

bar.df=melt(metabolism.data,id.vars=c("time","Sample"),measure.vars = c("GPP","Resp","NEP"),na.rm=TRUE)


bar.sum=summarySE(bar.df,measurevar="value",groupvars = c("time","variable","Sample"),na.rm=TRUE)
na.omit(bar.sum)
##component plots
gpp.bar.plot=ggplot(bar.sum,aes(time,group=Sample,shape=Sample,fill=Sample))+
  geom_point(data=subset(bar.sum,variable=="GPP"), 
             aes(y=value,shape=Sample),stat="identity",size=3,position=pd)+
  geom_line(data=subset(bar.sum,variable=="GPP"), 
            aes(y=value, linetype=Sample),width=.5,position=pd)+
  theme_classic()+
  geom_errorbar(data=subset(bar.sum,variable=="GPP"),
                aes(ymin=value-se,ymax=value+se,fill=Sample),
                stat="identity",width=.15,na.rm=T,position=pd)+
  scale_x_continuous(breaks=seq(0,30,5))+
  ylab(bquote(atop('GPP', 'mg O'[2]~''~cm^-2~''~hr^-1)))+
  xlab(NULL)+theme(legend.position = c(0.13,0.78),
                   legend.title=element_blank(),
                   axis.text=element_text(size=16),
                   axis.title=element_text(size=16),
                   legend.text=element_text(size=11),
                   legend.key = element_rect(color="transparent",fill="transparent"))+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))

resp.bar.plot=ggplot(bar.sum,aes(time,group=Sample,shape=Sample,fill=Sample))+
  geom_point(data=subset(bar.sum,variable=="Resp"),
             aes(y=value,shape=Sample),stat="identity",
             size=3,
             position=pd)+
  geom_line(data=subset(bar.sum,variable=="Resp"), 
            aes(y=value, linetype=Sample),
            width=.5,position=pd)+
  theme_classic()+
  geom_errorbar(data=subset(bar.sum,variable=="Resp"),
                aes(ymin=value-se,ymax=value+se,fill=Sample),
                stat="identity",width=.15,na.rm=T,position=pd)+
  scale_x_continuous(breaks=seq(0,30,5),position="top")+
  ylab(bquote(atop('Respiration','mg O'[2]~''~cm^-2~''~hr^-1)))+
  xlab(NULL)+
  theme( legend.title=element_blank(),
                   axis.text=element_text(size=16),
                   axis.title=element_text(size=16),
                   legend.text=element_text(size=14))+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))


nep.bar.plot=ggplot(bar.sum,aes(time,shape=Sample,group=Sample,fill=Sample))+
  geom_point(data=subset(bar.sum,variable=="NEP"),na.rm=T,
             aes(y=value, shape=Sample),stat="identity",size=3,position=pd)+
  geom_line(data=subset(bar.sum,variable=="NEP"),na.rm=T, 
            aes(y=value, linetype=Sample),width=.5,position=pd)+
  geom_hline(yintercept=0)+theme_classic()+
  geom_errorbar(data=subset(bar.sum,variable=="NEP"),
                aes(ymin=value-se,ymax=value+se,fill=Sample),
                stat="identity",width=.15,na.rm=T,position=pd)+
  scale_x_continuous(breaks=seq(0,30,5))+
  ylab(bquote(atop('NEP','mg O'[2]~''~cm^-2~''~hr^-1)))+
  xlab("Days of Incubation")+
  scale_y_continuous(breaks=seq(-1,1,0.5))+
  theme(legend.position = NULL,
        legend.title=element_blank(),
        axis.text=element_text(size=16),
        axis.title=element_text(size=16),
        legend.text=element_text(size=14))+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))

stacked.bar=ggarrange(gpp.bar.plot+theme(axis.text.x=element_blank()),
                      resp.bar.plot+theme(axis.text.x=element_blank(),legend.position="none"),
                      nep.bar.plot+theme(legend.position="none"),
                      nrow=3,common.legend = FALSE,align="v",heights=c(1,1,1.25))
stacked.bar
ggsave("metabolism.color.jpeg",width=8.5,height=8.5, units="in")
```



```{r Enzymes Figure 3}
## Day 21 plates were dropped/otherise
eea.df<-eea.df %>% 
  filter(time!=21) #filter out bad day

pd=position_dodge(width=0.8)

bg.sum=summarySE(eea.df,measurevar="BGT2",groupvars=c("time","Sample"))
nag.sum=summarySE(eea.df,measurevar="NAGT2",groupvars=c("time","Sample"))
p.sum=summarySE(eea.df,measurevar="PT2",groupvars=c("time","Sample"))

exp.plot.bg=ggplot(bg.sum,
                   aes(x=time,y=BGT2,group=Sample,shape=Sample,fill=Sample))+
  geom_point(position=pd,size=3)+
  geom_line(aes(linetype=Sample),position=pd)+
  geom_errorbar(aes(ymin=BGT2-se,ymax=BGT2+se),width=0.3,position=pd)+
  theme_classic()+
  ylab(bquote(atop(beta~'glucosidase', 
                   '( '*mu~'g'~cm^-2~h^-1~')')))+
  theme(legend.position=c(0.1,0.65),
        legend.title=element_blank())+
  scale_x_continuous(breaks=seq(0,30,5))+
  xlab("Days of Incubation")+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))


#exp.plot.bg


exp.plot.nag=ggplot(nag.sum,
                    aes(x=time,y=NAGT2,group=Sample,shape=Sample,fill=Sample))+
  geom_point(position=pd,size=3)+
  geom_line(aes(linetype=Sample),position=pd)+
  geom_errorbar(aes(ymin=NAGT2-se,ymax=NAGT2+se),width=0.3,position=pd)+
  theme_classic()+
  ylab(bquote(atop('N-acetyl- '*beta~'-D glucosaminidase',
                   '( '*mu~'g'~cm^-2~h^-1~')')))+
  theme(legend.position=c(0.05,0.85),
        legend.title=element_blank())+
  scale_x_continuous(breaks=seq(0,30,5))+
  xlab("Days of Incubation")+
  theme_classic()+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))
#exp.plot.nag


exp.plot.p=ggplot(p.sum,
                  aes(x=time,y=PT2,group=Sample,shape=Sample,fill=Sample))+
  geom_point(position=pd,size=3)+
  geom_line(aes(linetype=Sample),position=pd)+
  geom_errorbar(aes(ymin=PT2-se,ymax=PT2+se),width=0.3,position=pd)+
  ylab(bquote(atop('Phosphatase', '( '*mu~'g'~cm^-2~h^-1~')')))+xlab("Date")+
  scale_y_continuous(limits=c(0,200))+
  scale_x_continuous(breaks=seq(0,30,5))+
  theme(legend.position=c(0.05,0.85),
        legend.title=element_blank())+
  scale_x_continuous(breaks=seq(0,30,5))+
  xlab("Days of Incubation")+
  theme_classic()+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))
  
#exp.plot.p


enz.plots=ggarrange(exp.plot.bg+
                      theme(axis.text.x=element_blank(),
                            axis.title.x = element_blank()),
          exp.plot.nag+
            theme(legend.position = "none",
                  axis.text.x=element_blank(),
                  axis.title.x = element_blank()),
          exp.plot.p+
            theme(legend.position = "none"),
          nrow=3,align="v",common.legend = FALSE,heights=c(1,1,1.25))

enz.plots
ggsave("enz_plots_fig3_color.jpeg",width=8.5,height=8.5, units="in")
```
```{r Enz fig BW}
## Day 21 plates were dropped/otherise
eea.df<-eea.df %>% 
  filter(time!=21) #filter out bad day

pd=position_dodge(width=0.8)

bg.sum=summarySE(eea.df,measurevar="BGT2",groupvars=c("time","Sample"))
nag.sum=summarySE(eea.df,measurevar="NAGT2",groupvars=c("time","Sample"))
p.sum=summarySE(eea.df,measurevar="PT2",groupvars=c("time","Sample"))

exp.plot.bg=ggplot(bg.sum,
                   aes(x=time,y=BGT2,group=Sample,shape=Sample))+
  geom_point(position=pd,size=3,fill="black")+
  geom_line(aes(linetype=Sample),position=pd)+
  geom_errorbar(aes(ymin=BGT2-se,ymax=BGT2+se),width=0.3,position=pd)+
  theme_classic()+
  ylab(bquote(atop(beta~'glucosidase', 
                   '( '*mu~'g'~cm^-2~h^-1~')')))+
  theme(legend.position=c(0.1,0.65),
        legend.title=element_blank())+
  scale_x_continuous(breaks=seq(0,30,5))+
  xlab("Days of Incubation")+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))


exp.plot.bg


exp.plot.nag=ggplot(nag.sum,
                    aes(x=time,y=NAGT2,group=Sample,shape=Sample))+
  geom_point(position=pd,size=3,fill="black")+
  geom_line(aes(linetype=Sample),position=pd)+
  geom_errorbar(aes(ymin=NAGT2-se,ymax=NAGT2+se),width=0.3,position=pd)+
  theme_classic()+
  ylab(bquote(atop('N-acetyl- '*beta~'-D glucosaminidase',
                   '( '*mu~'g'~cm^-2~h^-1~')')))+
  theme(legend.position=c(0.05,0.85),
        legend.title=element_blank())+
  scale_x_continuous(breaks=seq(0,30,5))+
  xlab("Days of Incubation")+
  theme_classic()+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))
#exp.plot.nag


exp.plot.p=ggplot(p.sum,
                  aes(x=time,y=PT2,group=Sample,shape=Sample))+
  geom_point(position=pd,size=3,fill="black")+
  geom_line(aes(linetype=Sample),position=pd)+
  geom_errorbar(aes(ymin=PT2-se,ymax=PT2+se),width=0.3,position=pd)+
  ylab(bquote(atop('Phosphatase', '( '*mu~'g'~cm^-2~h^-1~')')))+xlab("Date")+
  scale_y_continuous(limits=c(0,200))+
  scale_x_continuous(breaks=seq(0,30,5))+
  theme(legend.position=c(0.05,0.85),
        legend.title=element_blank())+
  scale_x_continuous(breaks=seq(0,30,5))+
  xlab("Days of Incubation")+
  theme_classic()+
  scale_shape_manual(name="Sample",values=c(21,22,23,24,25))
  
#exp.plot.p


enz.plots=ggarrange(exp.plot.bg+
                      theme(axis.text.x=element_blank(),
                            axis.title.x = element_blank()),
          exp.plot.nag+
            theme(legend.position = "none",
                  axis.text.x=element_blank(),
                  axis.title.x = element_blank()),
          exp.plot.p+
            theme(legend.position = "none"),
          nrow=3,align="v",common.legend = FALSE,heights=c(1,1,1.25))

enz.plots
ggsave("enz_plots_fig3_black.jpeg",width=8.5,height=8.5, units="in")
```


The main effect appears to be in rates of respiration and consequently the NEP.  What other factors explain this?  We will use a desicion tree to identify the data that can best explaint he observed NEP and Rep effect
```{r NEP and Resp differentials}
#Bring in rabund data 

saveRDS(metabolism.data,"metdata.Rdata")
```

