---
title: "Metacommunity"
author: "Sam Dunn"
date: "September 25, 2018"
output: html_document
---


```{r setup}
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE, repos='http://cran.us.r-project.org')
    sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("ggplot2", 
              "plyr", 
              "reshape2", 
              "RColorBrewer", 
              "scales", 
              "grid",
              "VennDiagram","bibtex",
              "vegan",
              "RAM",
              "tidyr",
              "Rmisc","glue",
              "reshape","reshape2","lemon",
              "gapminder","magrittr","dplyr","ggpubr","gridExtra","MASS","patternplot","tibble","gplots","broom","data.table","devtools","lubridate","caret","glmulti","htmlTable")
ipak(packages)

met.data<-readRDS("metdata.Rdata")
alg.data<-readRDS("algae.Rdata")
bac.data<-readRDS("bacteria.Rdata")
its.data<-readRDS("fungus.Rdata")

bac<-bac.data %>% 
  gather(-taxlevel,-rankID,-taxon,-daughterlevels,-total,key="Sample",value="obs") %>% 
  mutate(type="bacteria")
alg<-alg.data %>% 
  gather(-taxlevel,-rankID,-taxon,-daughterlevels,-total,key="Sample",value="obs")%>% 
  mutate(type="alage")
its<-its.data %>% 
  gather(-taxlevel,-rankID,-taxon,-daughterlevels,-total,key="Sample",value="obs")%>% 
  mutate(type="fungus")


microbes<-rbind(bac,alg,its)

microbes<-microbes %>%   #rabund calculations
  group_by(type,Sample) %>% 
  mutate(total_obs=sum(obs),
         rabund=obs/total_obs)

microbes<-microbes %>% 
  separate(col="Sample",into=c("junk","Date","Substrate","Rep"),sep=c(1,7,-1)) %>%
  filter(Date!="DKC1", Date!="DKC2",Date!="DKC3",Substrate!="CR")
  
  
microbes$junk=NULL
microbes$Date=ymd(microbes$Date)

microbes$Substrate=factor(microbes$Substrate,levels=c("H","So","Sh","F","T"),labels=c("PVC","Soft PE","Sheet PE","PS","Tile"))

met.data<-plyr::rename(met.data,c("Date.Sampled"="Date","Sample"="Substrate"))

master<-left_join(microbes,met.data,by=c("Date","Substrate","Rep"))

```


Data are loaded, tidyed, and ready for analysis.  We will be using a process called feature selection to identiify model components that are good explanatory vriables for NEP.

```{r}
class.taxa<-master %>% 
  filter(taxlevel==3)

#remove clutter
class.taxa$taxlevel=NULL
class.taxa$rankID=NULL
class.taxa$daughterlevels=NULL
class.taxa$total=NULL
class.taxa$id=NULL
class.taxa<-na.omit(class.taxa)

#revlaue factors are numeric
tax.levels<-as.data.frame(levels(class.taxa$taxon))
tax.levels$code<-seq(1,length(tax.levels$`levels(class.taxa$taxon)`),1)

#glm
full<-glm(NEP~.,family="gaussian",data=class.taxa)
#summary(full)
step<-stepAIC(full,direction="both",trace=FALSE)
step$anova

#partition training and validation sets
intraining<-createDataPartition(class.taxa$NEP,p=0.80,list=FALSE)
training<-class.taxa[intraining,]
testing<-class.taxa[-intraining,]

#Lerning vector quantization
#control <- trainControl(method="repeatedcv", number=10, repeats=10)
#model <- train(NEP~., 
 #              data=training, 
 #              method="gbm",
   #            verbose=FALSE, 
   #            trControl=control)
#recursive feature selection
control<-rfeControl(functions=rfFuncs,method="cv",number=10)

#result<-rfe(class.taxa[,-which(names(class.taxa)=="NEP")],class.taxa$NEP,control=control)

```


```{r}

mod.dat<-class.taxa %>%
  filter(rabund>0.01) %>% 
  spread(key=taxon,value=rabund,fill=0) %>% 
  mutate(nep_dif=case_when(Substrate=="PS"~"neg",
                           Substrate=="Tile"~"neg",
                           TRUE~"pos"))

#Select for axa that have at least 1% relative abundance to make dataset manageable by glmulti
  

set.seed(42)
pos.dat<-mod.dat %>% 
  filter(nep_dif=="pos")
neg.dat<-mod.dat %>% 
  filter(nep_dif=="neg")

pos.dat<- dplyr::select(pos.dat,-c(Rep,obs,doy,Date,total_obs,Substrate,nep_dif,GPP,Resp))
neg.dat<- dplyr::select(neg.dat,-c(Rep,obs,doy,Date,total_obs,Substrate,nep_dif,GPP,Resp))
mod.dat<- dplyr::select(mod.dat,-c(Rep,obs,doy,Date,total_obs,Substrate,nep_dif,GPP,Resp))

mod_neg<-glmulti(data=neg.dat,NEP~.,method="g",level=1,chunks=4)
mod_pos<-glmulti(data=pos.dat,NEP~.,method="g",level=1,chunks=4)
full_mod<-glmulti(data=mod.dat,NEP~.,method="g",level=1,chunks=4)


summary(mod_pos)
summary(mod_neg)
summary(full_mod)


mod_pos.final<-lm(paste(mod_pos@formulas[1]), data=pos.dat)
pos_sum<-tidy(summary(mod_pos.final))
pos_sum$model="PE and PVC"



mod_neg.final<-lm(paste(mod_neg@formulas[1]),data=neg.dat)
neg_sum<-tidy(summary(mod_neg.final))
neg_sum$model="PS and Tile"


full_mod.final<-lm(paste(full_mod@formulas[1]),data=mod.dat)
full_sum<-tidy(summary(full_mod.final))
full_sum$model="All Data"

lm_model_outputs<-rbind(pos_sum,neg_sum,full_sum)
lm_model_outputs[,2:5]<-signif(lm_model_outputs[,2:5],4)


htmlTable(lm_model_outputs)



```

