---
title: "NBC Figures"
author: "Sam Dunn"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  
  html_document: default
---

```{r setup, echo=F}
#save.image(file='NBC_global.Rdata')

#attach('NBC_global.Rdata')
#rmarkdown::render("NBC figures.Rmd")  paste in console to render....source data not included so render button  non-functional

#opts_chunk$set(echo = FALSE, cache=FALSE)
library(knitr)
load(file="assays.Rdata")

```

```{r}
#Resp
lme.resp=anova(lme(Resp~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=metabolism.data))
#lme.resp

#GPP
lme.gpp=anova(lme(GPP~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=metabolism.data))
#lme.gpp

#NEP
lme.nep=anova(lme(NEP~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=metabolism.data))
#lme.nep

#BG
lme.bg=anova(lme(BGT2~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=eea.df))
#lme.bg

#NAG
lme.nag=anova(lme(NAGT2~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=eea.df))
#lme.nag

#P
lme.p=anova(lme(PT2~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=eea.df))
#lme.p

#Chl
lme.chl=anova(lme(chl_abs~Date.Sampled*Sample,random=list(id=pdBlocked(list(~1,pdIdent(~Sample-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=chl.data))
#lme.chl

#CV
cv.data.drop=droplevels(cv.data[-which(cv.data$Date.Sampled=='2017-08-15'),])
lme.cv=anova(lmer(OD_cm~Date.Sampled*Substrate+(Date.Sampled|Substrate),na.action=na.omit,data=cv.data.drop))
#lme.cv
#model fails to converge, basically there is a date effect but no effect of sample
lme.cv=anova(lm(OD_cm~Date.Sampled*Substrate,random=list(id=pdBlocked(list(~1,pdIdent(~Substrate-1),pdIdent(~Date.Sampled-1)))),method="ML",na.action=na.omit,data=cv.data))
#lme.cv

table1=list(lme.resp,lme.gpp,lme.nep,lme.bg,lme.nag,lme.p,lme.chl)

names(table1)=c("resp","gpp","nep","bg","nag","p","chl")
table1.df=do.call(rbind.data.frame,table1)
table1.df=cbind(rownames(table1.df),table1.df)
rownames(table1.df)=NULL
colnames(table1.df)[1]="assay"
tab.1<-table1.df%>%
  separate(assay,into=c("Assay","Factor"),extra="merge")

problem<-c(".",")")
tab.1$Factor<-tab.1$Factor%>% 
  gsub(pattern=")",replacement="") %>% 
  gsub(pattern="\\.",replacement=" ")






tab.1<-tab.1 %>% 
  filter(Factor!="Intercept")

tab.1[,4:6]<-tab.1[,4:6] %>% 
  signif(digits=3)

htmlTable::htmlTable(tab.1)
DT::datatable(tab.1,
          filter='top',
          extensions='Buttons',
          options = list(dom = 'Bfrtip',buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
```


```{r Table 2 (envfit vectors),warning=FALSE,message=FALSE}
library(formattable)
attach(its.spp.scrs)
attach(alg.spp.scrs)
attach(bac.spp.scrs)

its.spp.scrs$Community=c("Fungus")
alg.spp.scrs$Community=c("Algae")
bac.spp.scrs$Community=c("Bacteria")

tab.2=rbind(bac.spp.scrs,alg.spp.scrs,its.spp.scrs)
#tab.2$Assay
#tab.2
tab.2=tab.2[c(5,3,1,2,4)]
rownames(tab.2)=NULL
formattable(tab.2)
#kable(tab.2)
#pander(tab.2)
tab.2$Primer=NULL
tab.2$NMDS1=format(round(tab.2$NMDS1,4),nsmall=4)
tab.2$NMDS2=format(round(tab.2$NMDS2,4),nsmall=4)
tab.2=plyr::rename(tab.2,c(NMDS1="  NMDS 1  ",NMDS2="  NMDS 2  ",pvals="   p-values "))

table2=htmlTable::htmlTable(tab.2,rgroup=paste(c("Bacteria","Algae","Fungi")),
                            n.rgroup=c(7,5,nrow(tab.2)-12),
                            col.rgroup=c("none","#F7F7F7"),
                            rnames=FALSE,caption="Significant Vectors Fits",
                            css.cell= 'padding: 0px 15px 0px;') #FINALLY!  ADJUST THESE VALUES TO CHANGE PADDING
table2


```

```{r Table 3 (PERMANOVA),warning=FALSE,message=FALSE,eval=F}
library(formattable)
attach(bac.perm.tab)
attach(alg.perm.tab)
attach(its.perm.tab)

#its.perm.tab$Community=c("Fungus")
#alg.perm.tab$Community=c("Algae")
#bac.perm.tab$Community=c("Bacteria")

its.perm.tab$Parameter=rownames(its.perm.tab)
alg.perm.tab$Parameter=rownames(alg.perm.tab)
bac.perm.tab$Parameter=rownames(bac.perm.tab)

tab.3=rbind(bac.perm.tab,alg.perm.tab,its.perm.tab)
#tab.2$Assay
#tab.2

rownames(tab.3)=NULL
tab.3=tab.3[c(7,8,1,2,3,4,5,6)]

tab.3=plyr::rename(tab.3,c("Parameter"=" ","SumsOfSqs"="Sum of Sqs.","MeanSqs"="Mean Sqs."))
tab.3$Community=NULL

#tab.3$NMDS1=format(round(tab.2$NMDS1,4),nsmall=4)
#tab.3$NMDS2=format(round(tab.2$NMDS2,4),nsmall=4)
#tab.2=plyr::rename(tab.2,c(NMDS1="  NMDS 1  ",NMDS2="  NMDS 2  ",pvals="   p-values "))
tab.3=tab.3 %>% mutate_if(is.numeric, round, 4)

table3=htmlTable::htmlTable(tab.3,rgroup=paste(c("Bacteria","Algae","Fungi")),
                            n.rgroup=c(3,3,3),
                            col.rgroup=c("none","#F7F7F7"),
                            rnames=FALSE,
                            css.cell= 'padding: 0px 15px 0px;') #FINALLY!  ADJUST THESE VALUES TO CHANGE PADDING
table3
knitr::kable(table3)

```

```{r Figure 1 (Crystal violet)}

```

```{r Figure 2 (Metabolism)}

```

```{r Figure 3 (Enzymes)}

```

```{r Figure 4 (Shannon),warning=FALSE,message=FALSE}
library(ggpubr)
shannon.plot=ggarrange(shannon.div.16s+theme(axis.text.x=element_blank(),
                                axis.title.y=element_blank(),
                                axis.title.x=element_blank()),
          shannon.div.alg+theme(axis.text.x=element_blank(),
                                axis.title.x=element_blank()),
          shannon.div.its+theme(axis.title.y=element_blank()),
          common.legend = TRUE,nrow=3,legend = "bottom",align="v")
shannon.plot
ggsave("shannon.plot.jpeg",device = "jpeg",width=8.5,height=8.5, units="in")
```

```{r Figure 5 (NMDS with vectors),warning=FALSE,message=FALSE}
library(gridExtra)
library(lemon)
g2 <- function(a.gplot){
  if (!gtable::is.gtable(a.gplot))
    a.gplot <- ggplotGrob(a.gplot)
  gtable::gtable_filter(a.gplot, 'guide-box', fixed=TRUE)
}


legend <- g_legend(bac.nmds+theme(legend.position = "left",legend.box="horizontal"))
nmds.plot=ggarrange(bac.nmds+theme(legend.position='hidden'),
                    alg.nmds+theme(legend.position='hidden'),
                    its.nmds+theme(legend.position='hidden'),
                    legend,
                    ncol=2,nrow=2,widths=c(1,1,1,1))


nmds.plot
ggsave(nmds.plot, filename = "nmds.plot.jpeg",device="jpeg",width=8.5,height=8,units="in")

```

```{r Figure 6 (Venn Diagrams),warning=FALSE,message=FALSE}
library(gridExtra)
library(grid)
venn.plot=grid.arrange(gTree(children=bac.venn),gTree(children=alg.venn),gTree(children=its.venn),nrow=3)
ggsave(venn.plot, filename = "venn.plot.jpeg",device="jpeg",width=6,height=11,units="in")

```

```{r Supp Figure 1 (Env conditions),warning=FALSE,message=FALSE}

```

